### ISSUE TITLE
引入失败，import * as mars3d from 'mars3d' 这样写会报错

### ISSUE THREAD

**Issue by wangcs-study** [marsgis/mars3d-react-template#4]
![微信截图_20210721172108](https://user-images.githubusercontent.com/24839923/126464990-07191130-37d6-4976-a737-16154b7d8b14.png)
![微信截图_20210721172054](https://user-images.githubusercontent.com/24839923/126465013-3cba4e40-bdad-483d-9db9-ab5caf75007b.png)

**Comment by muyao1987** [comment]
参考 https://github.com/marsgis/mars3d-vue-template-cdn 用cdn方式引入cesium试下。cesium的集成容易出问题。

**Comment by muyao1987** [comment]
<link href="http://mars3d.cn/lib/Cesium/Widgets/widgets.css" rel="stylesheet" type="text/css" />
<script src="http://mars3d.cn/lib/Cesium/Cesium.js" type="text/javascript" ></script>


<link href="http://mars3d.cn/lib/mars3d/mars3d.css" rel="stylesheet" type="text/css" />
<script src="http://mars3d.cn/lib/mars3d/mars3d.js" type="text/javascript" ></script>

**Comment by muyao1987** [comment]
参考下面代码引入在线或本地的sdk 

 `

<link href="http://mars3d.cn/lib/Cesium/Widgets/widgets.css" rel="stylesheet" type="text/css" />
<script src="http://mars3d.cn/lib/Cesium/Cesium.js" type="text/javascript" ></script>


<link href="http://mars3d.cn/lib/mars3d/mars3d.css" rel="stylesheet" type="text/css" />
<script src="http://mars3d.cn/lib/mars3d/mars3d.js" type="text/javascript" ></script>  `
