### ISSUE TITLE
react项目模板运行不起来

### ISSUE THREAD

**Issue by myf-sky** [marsgis/mars3d-react-template#5]
模板下载下来后，安装完依赖，运行报错；
Html Webpack Plugin:
  ReferenceError: BASE_URL is not defined
  
  - loader.js:4 eval
    [index.html?.]/[_html-webpack-plugin@3.2.0@html-webpack-plugin]/lib/loader.js:4:11
  
  - loader.js:11 module.exports
    [index.html?.]/[_html-webpack-plugin@3.2.0@html-webpack-plugin]/lib/loader.js:11:3
  
  - index.js:284 
    [mars3d-react-template-master]/[_html-webpack-plugin@3.2.0@html-webpack-plugin]/index.js:284:18

**Comment by muyao1987** [comment]
感谢反馈，因为复制vue的类似cdn代码到public\index.html未修改造成的错误，已修复处理
